CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  event_date DATE NOT NULL,
  event_time TIME NULL,
  city VARCHAR(255) NOT NULL,
  location_name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NULL,
  description_short TEXT NOT NULL,
  description_long TEXT NOT NULL,
  image_path VARCHAR(500) NULL,
  status ENUM('upcoming','past','draft') DEFAULT 'draft',
  is_featured TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS artworks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT NOT NULL,
  image_path VARCHAR(500) NOT NULL,
  collection_name VARCHAR(255) NULL,
  year VARCHAR(20) NULL,
  is_visible TINYINT(1) DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tour_locations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  date_from DATE NOT NULL,
  date_to DATE NULL,
  status ENUM('current','upcoming','past','draft') DEFAULT 'draft',
  google_maps_url VARCHAR(500) NULL,
  description TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  first_name VARCHAR(255) NULL,
  source VARCHAR(255) NULL,
  consent_privacy TINYINT(1) DEFAULT 0,
  double_opt_in_token VARCHAR(255) NULL,
  double_opt_in_confirmed_at DATETIME NULL,
  ticket_token VARCHAR(255) UNIQUE,
  ticket_sent_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(100) NULL,
  user_agent TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ticket_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subscriber_id INT UNSIGNED NULL,
  email VARCHAR(255),
  ticket_token VARCHAR(255),
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50),
  error_message TEXT NULL,
  CONSTRAINT fk_ticket_logs_subscriber FOREIGN KEY (subscriber_id) REFERENCES newsletter_subscribers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
