-- S-ART / Shary on Tour - Schema

CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  event_date DATE NOT NULL,
  event_time TIME NULL,
  city VARCHAR(255) NOT NULL,
  location_name VARCHAR(255) NULL,
  address VARCHAR(255) NULL,
  description_short TEXT NULL,
  description_long TEXT NULL,
  image_path VARCHAR(500) NULL,
  status ENUM('upcoming','past','draft') DEFAULT 'upcoming',
  is_opening TINYINT(1) DEFAULT 0,
  max_tickets INT UNSIGNED DEFAULT 0,
  google_maps_url VARCHAR(500) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tickets (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_id INT UNSIGNED NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NULL,
  ticket_id VARCHAR(64) NOT NULL UNIQUE,
  status ENUM('active','disabled') DEFAULT 'active',
  ip_address VARCHAR(100) NULL,
  user_agent TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_event_email (event_id, email),
  CONSTRAINT fk_tickets_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS galleries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_id INT UNSIGNED NOT NULL,
  image_path VARCHAR(500) NOT NULL,
  caption VARCHAR(255) NULL,
  sort_order INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_galleries_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  location_optional VARCHAR(255) NULL,
  consent_privacy TINYINT(1) DEFAULT 1,
  ip_address VARCHAR(100) NULL,
  user_agent TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ticket_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ticket_id VARCHAR(64) NULL,
  email VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL,
  error_message TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
